In [10]:
!pip install PyDrive

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [14]:
# "/content/drive/MyDrive/Automobile.csv"

import pandas as pd
# Load the CSV file into a Pandas DataFrame
df = pd.read_csv("/content/drive/MyDrive/Automobile.csv")

In [15]:
# Display the first 30 rows.
df.head(30)

symboling  normalized_losses         make fuel_type aspiration  \
0           3                168  alfa-romero       gas        std   
1           3                168  alfa-romero       gas        std   
2           1                168  alfa-romero       gas        std   
3           2                164         audi       gas        std   
4           2                164         audi       gas        std   
5           2                161         audi       gas        std   
6           1                158         audi       gas        std   
7           1                168         audi       gas        std   
8           1                158         audi       gas      turbo   
9           2                192          bmw       gas        std   
10          0                192          bmw       gas        std   
11          0                188          bmw       gas        std   
12          0                188          bmw       gas        std   
13          1                149          bmw       gas        std   
14          0                149          bmw       gas        std   
15          0                149          bmw       gas        std   
16          0                149          bmw       gas        std   
17          2                121    chevrolet       gas        std   
18          1                 98    chevrolet       gas        std   
19          0                 81    chevrolet       gas        std   
20          1                118        dodge       gas        std   
21          1                118        dodge       gas        std   
22          1                118        dodge       gas      turbo   
23          1                148        dodge       gas        std   
24          1                148        dodge       gas        std   
25          1                148        dodge       gas        std   
26          1                148        dodge       gas      turbo   
27         -1                110        dodge       gas        std   
28          3                145        dodge       gas      turbo   
29          2                137        honda       gas        std   

   number_of_doors   body_style drive_wheels engine_location  wheel_base  ...  \
0              two  convertible          rwd           front        88.6  ...   
1              two  convertible          rwd           front        88.6  ...   
2              two    hatchback          rwd           front        94.5  ...   
3             four        sedan          fwd           front        99.8  ...   
4             four        sedan          4wd           front        99.4  ...   
5              two        sedan          fwd           front        99.8  ...   
6             four        sedan          fwd           front       105.8  ...   
7             four        wagon          fwd           front       105.8  ...   
8             four        sedan          fwd           front       105.8  ...   
9              two        sedan          rwd           front       101.2  ...   
10            four        sedan          rwd           front       101.2  ...   
11             two        sedan          rwd           front       101.2  ...   
12            four        sedan          rwd           front       101.2  ...   
13            four        sedan          rwd           front       103.5  ...   
14            four        sedan          rwd           front       103.5  ...   
15             two        sedan          rwd           front       103.5  ...   
16            four        sedan          rwd           front       110.0  ...   
17             two    hatchback          fwd           front        88.4  ...   
18             two    hatchback          fwd           front        94.5  ...   
19            four        sedan          fwd           front        94.5  ...   
20             two    hatchback          fwd           front        93.7  ...   
21             two    hatchback          fwd       

In [16]:
# Print column names
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [17]:
# Print No of Rows & Columns
df.shape

(201, 26)

In [18]:
#Find the Data Types of every column & check if there are any mismatch
df.dtypes

symboling                int64
normalized_losses        int64
make                    object
fuel_type               object
aspiration              object
number_of_doors         object
body_style              object
drive_wheels            object
engine_location         object
wheel_base             float64
length                 float64
width                  float64
height                 float64
curb_weight              int64
engine_type             object
number_of_cylinders     object
engine_size              int64
fuel_system             object
bore                   float64
stroke                 float64
compression_ratio      float64
horsepower               int64
peak_rpm                 int64
city_mpg                 int64
highway_mpg              int64
price                    int64
dtype: object

In [19]:
# What are the minimum & maximum price of the car & state fuel type they belong to
min_price = df["price"].min()
max_price = df["price"].max()
min_fuel_type = df[df["price"]==min_price]['fuel_type'].values[0]
max_fuel_type = df[df["price"]==max_price]['fuel_type'].values[0]
print(f"Min Price:{min_price},Fuel Type:{min_fuel_type}")
print(f"Max Price:{max_price},Fuel Type:{max_fuel_type}")


Min Price:5118,Fuel Type:gas
Max Price:45400,Fuel Type:gas


In [20]:
#List all the unique engine types
unique_engine = df["engine_type"].unique()
print(unique_engine)

['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf']


In [21]:
# Find the horsepower range
min_horsepower = df['horsepower'].min()
max_horsepower = df['horsepower'].max()
Horsepower_Range = max_horsepower - min_horsepower
print("Min_horsepower: ",min_horsepower)
print("Max_horsepower: ",max_horsepower)
print("Horsepower_Range: ",Horsepower_Range)

Min_horsepower:  48
Max_horsepower:  262
Horsepower_Range:  214


In [22]:
df.columns

Index(['symboling', 'normalized_losses', 'make', 'fuel_type', 'aspiration',
       'number_of_doors', 'body_style', 'drive_wheels', 'engine_location',
       'wheel_base', 'length', 'width', 'height', 'curb_weight', 'engine_type',
       'number_of_cylinders', 'engine_size', 'fuel_system', 'bore', 'stroke',
       'compression_ratio', 'horsepower', 'peak_rpm', 'city_mpg',
       'highway_mpg', 'price'],
      dtype='object')

In [23]:
# What is the average mpg in cities & highway. Which is better?

average_city_mpg = df["city_mpg"].mean()
average_highway_mpg = df['highway_mpg'].mean()
print("Average City MPG:",average_city_mpg)
print("AVerage Highway MPG:",average_highway_mpg)
if average_city_mpg > average_highway_mpg:
    print("City MPG is higher")
else:
    print("Highway MPG is Higher")

Average City MPG: 25.17910447761194
AVerage Highway MPG: 30.686567164179106
Highway MPG is Higher


In [24]:
#What are the different Automobile makes present & which has maximum count
print(df["make"].value_counts())
print(f"Most common make: {df['make'].value_counts().idxmax()}")

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              6
saab              6
porsche           4
jaguar            3
chevrolet         3
alfa-romero       3
isuzu             2
renault           2
mercury           1
Name: count, dtype: int64
Most common make: toyota


In [25]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
#Retrieve the row where Name == "Charlie" using .loc[].
print(df2.loc[df2["Name"] == "Charlie"])
#Select only the Age and Score columns for "Alice" and "Bob" using .loc[].
print(df2.loc[df2["Name"].isin(["Alice", "Bob"]), ["Age", "Score"]])

      Name  Age  Score
2  Charlie   22     78
   Age  Score
0   24     85
1   27     90


In [26]:
#Retrieve the second row using .iloc[].
print(df2.iloc[1])
#Extract the last two rows using .iloc[].
print(df2.iloc[-2:])

Name     Bob
Age       27
Score     90
Name: 1, dtype: object
      Name  Age  Score
2  Charlie   22     78
3    David   32     88


In [27]:
df3 = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
#Select only IT employees
print(df3[df3["Department"] == "IT"])
#Select employees with a salary greater than 55,000.
print(df3[df3["Salary"]>55000])

  Employee  Salary Department
0     John   50000         IT
2      Bob   55000         IT
  Employee  Salary Department
1    Alice   60000         HR
3    David   65000    Finance


In [28]:
df4 = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
#Converts marks below 50 to "Fail", and 50 or above to "Pass"
def pass_fail(marks):
    return "Fail" if marks<50 else "Pass"

#Apply this function to the "Marks" column and create a new column "Result".
df4["Result"] = df4["Marks"].apply(pass_fail)
print(df4)


  Student  Marks Result
0       A     45   Fail
1       B     78   Pass
2       C     62   Pass
3       D     90   Pass


In [29]:
pass_fail(34)

'Fail'

In [30]:
pass_fail(98)

'Pass'

In [31]:
#Create a NumPy array with values from 1 to 12.
import numpy as np
arr = np.arange(1,13)
print(arr)
#Reshape it into a 3x4 matrix.
arr1= arr.reshape(3,4)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
#Element-wise multiplication of a and b.
print(a*b)
#Add 5 to each element of a using broadcasting
print(a+5)

[10 40 90]
[6 7 8]


In [33]:
arr1 = np.array([[3, 7, 2], [4, 9, 6]])
# Find the maximum value in the entire array.
print(arr1.max())
# Find the minimum value in each row.
print(arr1.min(axis=1))

9
[2 4]


In [34]:
df5 = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
#Group the DataFrame by "Department" and calculate the average salary per department
print(df5.groupby("Department")["Salary"].mean())

Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [35]:
df6 = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
#Sort the DataFrame by Population in descending order
df_sorted = df6.sort_values(by="Population", ascending=False)

print(df_sorted)

          City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000


In [36]:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
#Retrieve the sales value for City A in the South Region using multi-indexing.
sales_value = df.loc[("South", "A"), "Sales"]

print(sales_value)

180


In [37]:
# Generate a 5x4 NumPy array with random integers between 10 and 99
array = np.random.randint(10, 100, size=(5, 4))

# Convert it into a Pandas DataFrame with specified column names
df = pd.DataFrame(array, columns=["A", "B", "C", "D"])

print(df)

    A   B   C   D
0  59  83  24  69
1  20  49  58  71
2  60  65  94  15
3  27  13  29  37
4  72  55  53  99


In [38]:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})

#Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.
df.loc[df["Attendance"] < 60, "Marks"] = 0
df

Student  Marks  Attendance
0    Alice     88          85
1      Bob      0          50
2  Charlie     76          90
3    David     90          60

In [46]:
# Create a sample DataFrame
data = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "Department": ["IT", "Finance", "IT", "HR", "Finance"],
    "Salary": [70000, 80000, 50000, 45000, 90000],
    "Experience": [6, 8, 4, 3, 7]
}

df = pd.DataFrame(data)

# Save the DataFrame to a CSV file
df.to_csv("employees.csv", index=False)

In [47]:
# Read the CSV file
df = pd.read_csv("employees.csv")

# Apply the query to select employees from 'IT' or 'Finance' department
# with Salary > 60,000 and at least 5 years of experience
result = df.query('Department in ["IT", "Finance"] and Salary > 60000 and Experience >= 5')

print(result)

   EmployeeID Department  Salary  Experience
0         101         IT   70000           6
1         102    Finance   80000           8
4         105    Finance   90000           7


In [48]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
#Find the average salary for each department, but only for employees with at least 5 years of experience.

# Filter the DataFrame for employees with at least 5 years of experience
filtered_df = df[df["Experience"] >= 5]

# Group by department and calculate the average salary
average_salary = filtered_df.groupby("Department")["Salary"].mean()

print(average_salary)

Department
Finance    72000.000000
IT         71666.666667
Name: Salary, dtype: float64


In [49]:
# Create a 5x5 NumPy array with random values between 1 and 100
arr = np.random.randint(1, 101, size=(5, 5))
print("Array:")
print(arr)

Array:
[[27 88 31 35 58]
 [87 79  6 51 96]
 [65 45 73 20 50]
 [99 42  3 25 38]
 [19  6  2 88 39]]


In [50]:
# Extract only even numbers
even_numbers = arr[arr % 2 == 0]
print("\nEven Numbers:")
print(even_numbers)


Even Numbers:
[88 58  6 96 20 50 42 38  6  2 88]


In [51]:
# Extract values from the last row and last column
last_row = arr[-1, :]
last_column = arr[:, -1]

print("\nLast Row:")
print(last_row)
print("\nLast Column:")
print(last_column)


Last Row:
[19  6  2 88 39]

Last Column:
[58 96 50 38 39]


In [52]:
# Replace all values greater than 50 with 0
arr[arr > 50] = 0

print("\nArray after replacing values greater than 50 with 0:")
print(arr)


Array after replacing values greater than 50 with 0:
[[27  0 31 35  0]
 [ 0  0  6  0  0]
 [ 0 45  0 20 50]
 [ 0 42  3 25 38]
 [19  6  2  0 39]]


In [53]:
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])

#Perform matrix multiplication and output the result
result = A @ B

print("Matrix multiplication result:")
print(result)

Matrix multiplication result:
[[22 34]
 [46 74]]


In [54]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])

#Find the elements that are common in both arrays.
common_elements = np.intersect1d(arr1, arr2)

#Find the elements that are only present in arr1 but not in arr2
only_in_arr1 = np.setdiff1d(arr1, arr2)

print("Common elements:", common_elements)
print("Elements in arr1 but not in arr2:", only_in_arr1)


Common elements: [30 40]
Elements in arr1 but not in arr2: [10 20 50 60]


In [56]:
#You are given the following DataFrame:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
#Task
#Sort the players by descending Score.
#Assign ranking to each player (1st, 2nd, 3rd...) without skipping numbers

In [57]:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})

# Sort the players by descending Score
df_sorted = df.sort_values(by="Score", ascending=False)

# Assign ranking to each player
df_sorted["Rank"] = range(1, len(df_sorted) + 1)

# Output the result
print(df_sorted)

  Player  Score  Rank
1      B    450     1
2      C    300     2
0      A    200     3
3      D    150     4


In [59]:
df = pd.read_csv('big data.csv')
df.columns

FileNotFoundError: [Errno 2] No such file or directory: 'big data.csv'

In [60]:
df.shape

(4, 2)

In [61]:
import pandas as pd

# Define the columns to load
columns_to_load = ["customer_id", "price"]

# Use the "dtype" argument to specify the most memory-efficient data type for CustomerID
# Assuming "CustomerID" is an integer or a category (use 'category' for better memory efficiency)
dtype = {"customer_id": "category"}

# Load the first 100,000 rows and only the specified columns
df = pd.read_csv("big data.csv", usecols=columns_to_load, nrows=100000, dtype=dtype)

# Output the first few rows to verify
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'big data.csv'

In [63]:
import pandas as pd
import numpy as np

# Set the number of records
num_records = 1000000

# Generate synthetic data
data = {
    "CustomerID": np.random.randint(1000, 9999, size=num_records),
    "PurchaseAmount": np.random.uniform(10, 1000, size=num_records)
}

# Create a DataFrame
df = pd.DataFrame(data)

# Save to CSV
df.to_csv("big_data.csv", index=False)

In [64]:
# Define the columns to load
columns_to_load = ["CustomerID", "PurchaseAmount"]

# Use the "dtype" argument to specify the most memory-efficient data type for CustomerID
# Assuming "CustomerID" is an integer or a category (use 'category' for better memory efficiency)
dtype = {"CustomerID": "category"}

# Load the first 100,000 rows and only the specified columns
df = pd.read_csv("big_data.csv", usecols=columns_to_load, nrows=100000, dtype=dtype)
df["PurchaseAmount"] = df["PurchaseAmount"].round(2)
print(df)

      CustomerID  PurchaseAmount
0           7859          866.21
1           2863          682.28
2           6787          723.41
3           1568           49.40
4           9341          389.89
...          ...             ...
99995       1746          687.79
99996       2397          730.84
99997       8363          184.51
99998       5298          592.49
99999       6918          802.27

[100000 rows x 2 columns]
