In [1]:
#Write a Python program that swaps two numbers without using a third variable
a= 13
b = 15
print("Before swapping:",a,b)

a,b = b,a

print("After Swapping: ",a,b)

Before swapping: 13 15
After Swapping:  15 13


In [2]:
#You have a nested list:

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#a) Extract and print the middle element from the nested list.
print("Middle Element:",data[1])
print("Middle item:",data[1][1])

#Flatten the list into a single list [1, 2, 3, 4, 5, 6, 7, 8, 9] without using loops

#using list comprehension
flat_list = [item for i in data for item in i]
print("flattened list:",flat_list)


Middle Element: [4, 5, 6]
Middle item: 5
flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
#Question 3
#Given:
values = (100, 200, 300)
print(values)
#a) Unpack this tuple into three variables and print them.

a,b,c = values
print("a:",a)
print("b:",b)
print("c:",c)
#Swap the values without using a temporary variable.
a,b,c = b,c,a
print("After swapping:",a,b,c)

(100, 200, 300)
a: 100
b: 200
c: 300
After swapping: 200 300 100


In [5]:
'''Create a dictionary where:
•	Keys are tuples representing (x, y) coordinates.
•	Values are the sum of x and y.
Example:
{ (1,2): 3, (3,4): 7, (5,6): 11 }
Write a function to retrieve the sum for a given coordinate'''

coordinates = {
    (3,5): 8,
    (5, 4): 9,
    (7, 6): 13
}
def get_sum(coord_dict,x,y):
    return coord_dict.get((x,y))

print(get_sum(coordinates,3,5))


8


In [6]:
'''Write a function outer_function(a, b) that:
•	Contains an inner function to calculate a² + b².
•	Returns the result.
Call outer_function(3, 4) and print the result.
'''
def outer_function(a,b):
    def inner_function():
      return a**2 + b**2
    return inner_function()

result = outer_function(3,4)
print("Result:",result)

Result: 25


In [7]:
'''You are given a list:
numbers = [1, 2, 3, 4, 5]
Use a lambda function and map() to generate a list where each number is cubed.
'''
numbers = [1,2,3,4,5]
cubed_numbers = list(map(lambda x: x**3,numbers))
print("Cubed Numbers:",cubed_numbers)


Cubed Numbers: [1, 8, 27, 64, 125]


In [8]:
'''Write a recursive function to calculate the sum of digits of a given number.
Example:
Input: 1234
Output: 10  (1+2+3+4)
'''
def sum_of_digits(n):
    if n == 0:
        return 0
    return (n % 10) + sum_of_digits(n // 10)

# Example Usage:
num = 1234
print(sum_of_digits(num))

10


In [9]:
'''Generate a list of all numbers between 1 and 100 that:
•	Are divisible by 5
•	But not by 3
Use list comprehension.
'''
numbers = [num for num in range(1, 101) if num % 5 == 0 and num % 3 != 0]

print(numbers)


[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]


In [10]:
'''Given:
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
Sort this dictionary by values in descending order and print the result.
'''
scores = {"Alice": 90, "Bob": 85, "Eve": 92}

# Sorting by values in descending order
sorted_scores = dict(sorted(scores.items(), key=lambda item: item[1], reverse=True))

print(sorted_scores)

{'Eve': 92, 'Alice': 90, 'Bob': 85}


In [11]:
'''Write a Python function that takes a string as input and returns:
•	A set of unique characters in the string.
•	The number of unique characters.
Example:
Input: "hello"
Output: {'h', 'e', 'l', 'o'}, 4
'''
def unique_characters(s):
    unique_chars = set(s)
    return unique_chars, len(unique_chars)

# Example Usage:
#result = unique_chars_info("hello")
#print(result)

input_string = "hello"
unique_set, unique_count = unique_characters(input_string)

print("Unique Characters:", unique_set)
print("Number of Unique Characters:", unique_count)


Unique Characters: {'h', 'e', 'l', 'o'}
Number of Unique Characters: 4


In [12]:

'''Given two tuples:
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
Find and print the common elements.
'''
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)

# Finding common elements using set intersection
common_elements = set(t1) & set(t2)

print(common_elements)

{4, 5}


In [13]:
'''Given a dictionary:
data = {"A": 1, "B": 2, "C": 3}
Write a program to swap keys and values:
Output: {1: "A", 2: "B", 3: "C"}
'''

data = {"A": 1, "B": 2, "C": 3}

# Swapping keys and values
swapped_data = {v: k for k, v in data.items()}

print(swapped_data)

{1: 'A', 2: 'B', 3: 'C'}


In [14]:
'''Write a function that takes two numbers as input and returns:
1.	Their sum
2.	Their difference
3.	Their product
4.	Their quotient
Print all four results.
'''
def perform_operations(num1, num2):
    sum_result = num1 + num2
    diff_result = num1 - num2
    prod_result = num1 * num2
    # Handling division by zero
    if num2 != 0:
        quot_result = num1 / num2
    else:
        quot_result = "Undefined (division by zero)"

    return sum_result, diff_result, prod_result, quot_result

# Example Usage:
num1 = 10
num2 = 5
sum_result, diff_result, prod_result, quot_result = perform_operations(num1, num2)

print("Sum:", sum_result)
print("Difference:", diff_result)
print("Product:", prod_result)
print("Quotient:", quot_result)


Sum: 15
Difference: 5
Product: 50
Quotient: 2.0


In [15]:

'''Write a function to find the second largest number in a given list without using sort().
Example:
Input: [10, 20, 4, 45, 99]
Output: 45
'''


def second_largest(numbers):
    # Initialize the two largest numbers
    first, second = float('-inf'), float('-inf')

    for num in numbers:
        if num > first:
            second = first
            first = num
        elif num > second and num != first:
            second = num

    return second

# Example Usage:
numbers = [10, 20, 4, 45, 99]
print("Second Largest Number:", second_largest(numbers))

Second Largest Number: 45


In [16]:
'''Given a list of numbers and a target sum, find all pairs in the list that add up to the target.
Example:
Input: [2, 4, 3, 7, 1, 9], Target: 10
Output: [(3, 7), (1, 9)]'''

def find_pairs(numbers, target):
    seen = set()
    pairs = []

    for num in numbers:
        complement = target - num
        if complement in seen:
            pairs.append((complement, num))
        seen.add(num)

    return pairs

# Example Usage:
numbers = [2, 4, 3, 7, 1, 9]
target = 10
result = find_pairs(numbers, target)

print("Pairs:", result)

Pairs: [(3, 7), (1, 9)]


In [17]:
'''You are given the following Pandas DataFrame:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Write a one-liner to filter and display only rows where Age is greater than 25
'''
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
df[df["Age"] > 25]

Name  Age  Score
1    Bob   27     90
3  David   32     88

In [18]:
'''You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Write a Pandas command to calculate the average salary per department
'''

import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
df.groupby("Department")["Salary"].mean()


Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64

In [19]:
'''Write a program to create a 5x5 NumPy matrix where:
•	The diagonal elements are 1
•	All other elements are 0
'''
import numpy as np

# Create a 5x5 identity matrix
matrix = np.eye(5)

print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:

'''Given two NumPy arrays:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
Perform element-wise:
1.	Addition
2.	Multiplication
3.	Power (a^b)
Print the results.
'''
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# 1. Element-wise Addition
addition_result = a + b

# 2. Element-wise Multiplication
multiplication_result = a * b

# 3. Element-wise Power (a^b)
power_result = a ** b

# Print the results
print("Addition Result:", addition_result)
print("Multiplication Result:", multiplication_result)
print("Power Result (a^b):", power_result)

Addition Result: [11 22 33 44]
Multiplication Result: [ 10  40  90 160]
Power Result (a^b): [              1         1048576 205891132094649               0]


In [21]:
'''arr = np.array([10, 25, 39, 50, 19])
Write a one-liner to find the index of the maximum value.
'''
arr = np.array([10, 25, 39, 50, 19])
index_max = arr.argmax()
print(index_max)

3
